#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verzus.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspnet-Verzus-20120828131727")]
	public partial class VerzusLinqSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVerzus(Verzus instance);
    partial void UpdateVerzus(Verzus instance);
    partial void DeleteVerzus(Verzus instance);
    partial void InsertVerzusItemType(VerzusItemType instance);
    partial void UpdateVerzusItemType(VerzusItemType instance);
    partial void DeleteVerzusItemType(VerzusItemType instance);
    partial void InsertVerzusItem(VerzusItem instance);
    partial void UpdateVerzusItem(VerzusItem instance);
    partial void DeleteVerzusItem(VerzusItem instance);
    #endregion
		
		public VerzusLinqSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aspnet_Verzus_20120828131727ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VerzusLinqSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerzusLinqSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerzusLinqSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VerzusLinqSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Verzus> Verzus
		{
			get
			{
				return this.GetTable<Verzus>();
			}
		}
		
		public System.Data.Linq.Table<VerzusItemType> VerzusItemTypes
		{
			get
			{
				return this.GetTable<VerzusItemType>();
			}
		}
		
		public System.Data.Linq.Table<VerzusItem> VerzusItems
		{
			get
			{
				return this.GetTable<VerzusItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Verzus")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Verzus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _VerzusId;
		
		private long _VerzusItem1;
		
		private long _VerzusItem2;
		
		private long _VerzusItemContext;
		
		private string _VerzusUrlKey;
		
		private long _VerzusCreatedBy;
		
		private System.DateTime _VerzusDateAdded;
		
		private EntityRef<VerzusItem> _VerzusItem;
		
		private EntityRef<VerzusItem> _VerzusItem3;
		
		private EntityRef<VerzusItem> _VerzusItem4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVerzusIdChanging(long value);
    partial void OnVerzusIdChanged();
    partial void OnVerzusItem1Changing(long value);
    partial void OnVerzusItem1Changed();
    partial void OnVerzusItem2Changing(long value);
    partial void OnVerzusItem2Changed();
    partial void OnVerzusItemContextChanging(long value);
    partial void OnVerzusItemContextChanged();
    partial void OnVerzusUrlKeyChanging(string value);
    partial void OnVerzusUrlKeyChanged();
    partial void OnVerzusCreatedByChanging(long value);
    partial void OnVerzusCreatedByChanged();
    partial void OnVerzusDateAddedChanging(System.DateTime value);
    partial void OnVerzusDateAddedChanged();
    #endregion
		
		public Verzus()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public long VerzusId
		{
			get
			{
				return this._VerzusId;
			}
			set
			{
				if ((this._VerzusId != value))
				{
					this.OnVerzusIdChanging(value);
					this.SendPropertyChanging();
					this._VerzusId = value;
					this.SendPropertyChanged("VerzusId");
					this.OnVerzusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusItem1", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public long VerzusItem1
		{
			get
			{
				return this._VerzusItem1;
			}
			set
			{
				if ((this._VerzusItem1 != value))
				{
					if (this._VerzusItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVerzusItem1Changing(value);
					this.SendPropertyChanging();
					this._VerzusItem1 = value;
					this.SendPropertyChanged("VerzusItem1");
					this.OnVerzusItem1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusItem2", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public long VerzusItem2
		{
			get
			{
				return this._VerzusItem2;
			}
			set
			{
				if ((this._VerzusItem2 != value))
				{
					if (this._VerzusItem3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVerzusItem2Changing(value);
					this.SendPropertyChanging();
					this._VerzusItem2 = value;
					this.SendPropertyChanged("VerzusItem2");
					this.OnVerzusItem2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusItemContext", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public long VerzusItemContext
		{
			get
			{
				return this._VerzusItemContext;
			}
			set
			{
				if ((this._VerzusItemContext != value))
				{
					if (this._VerzusItem4.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVerzusItemContextChanging(value);
					this.SendPropertyChanging();
					this._VerzusItemContext = value;
					this.SendPropertyChanged("VerzusItemContext");
					this.OnVerzusItemContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusUrlKey", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string VerzusUrlKey
		{
			get
			{
				return this._VerzusUrlKey;
			}
			set
			{
				if ((this._VerzusUrlKey != value))
				{
					this.OnVerzusUrlKeyChanging(value);
					this.SendPropertyChanging();
					this._VerzusUrlKey = value;
					this.SendPropertyChanged("VerzusUrlKey");
					this.OnVerzusUrlKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusCreatedBy", DbType="BigInt NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public long VerzusCreatedBy
		{
			get
			{
				return this._VerzusCreatedBy;
			}
			set
			{
				if ((this._VerzusCreatedBy != value))
				{
					this.OnVerzusCreatedByChanging(value);
					this.SendPropertyChanging();
					this._VerzusCreatedBy = value;
					this.SendPropertyChanged("VerzusCreatedBy");
					this.OnVerzusCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerzusDateAdded", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.DateTime VerzusDateAdded
		{
			get
			{
				return this._VerzusDateAdded;
			}
			set
			{
				if ((this._VerzusDateAdded != value))
				{
					this.OnVerzusDateAddedChanging(value);
					this.SendPropertyChanging();
					this._VerzusDateAdded = value;
					this.SendPropertyChanged("VerzusDateAdded");
					this.OnVerzusDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus", Storage="_VerzusItem", ThisKey="VerzusItem1", OtherKey="ItemId", IsForeignKey=true)]
		public VerzusItem VerzusItem
		{
			get
			{
				return this._VerzusItem.Entity;
			}
			set
			{
				VerzusItem previousValue = this._VerzusItem.Entity;
				if (((previousValue != value) 
							|| (this._VerzusItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VerzusItem.Entity = null;
						previousValue.Verzus.Remove(this);
					}
					this._VerzusItem.Entity = value;
					if ((value != null))
					{
						value.Verzus.Add(this);
						this._VerzusItem1 = value.ItemId;
					}
					else
					{
						this._VerzusItem1 = default(long);
					}
					this.SendPropertyChanged("VerzusItem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus1", Storage="_VerzusItem3", ThisKey="VerzusItem2", OtherKey="ItemId", IsForeignKey=true)]
		public VerzusItem VerzusItem3
		{
			get
			{
				return this._VerzusItem3.Entity;
			}
			set
			{
				VerzusItem previousValue = this._VerzusItem3.Entity;
				if (((previousValue != value) 
							|| (this._VerzusItem3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VerzusItem3.Entity = null;
						previousValue.Verzus1.Remove(this);
					}
					this._VerzusItem3.Entity = value;
					if ((value != null))
					{
						value.Verzus1.Add(this);
						this._VerzusItem2 = value.ItemId;
					}
					else
					{
						this._VerzusItem2 = default(long);
					}
					this.SendPropertyChanged("VerzusItem3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus2", Storage="_VerzusItem4", ThisKey="VerzusItemContext", OtherKey="ItemId", IsForeignKey=true)]
		public VerzusItem VerzusItem4
		{
			get
			{
				return this._VerzusItem4.Entity;
			}
			set
			{
				VerzusItem previousValue = this._VerzusItem4.Entity;
				if (((previousValue != value) 
							|| (this._VerzusItem4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VerzusItem4.Entity = null;
						previousValue.Verzus2.Remove(this);
					}
					this._VerzusItem4.Entity = value;
					if ((value != null))
					{
						value.Verzus2.Add(this);
						this._VerzusItemContext = value.ItemId;
					}
					else
					{
						this._VerzusItemContext = default(long);
					}
					this.SendPropertyChanged("VerzusItem4");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._VerzusItem = default(EntityRef<VerzusItem>);
			this._VerzusItem3 = default(EntityRef<VerzusItem>);
			this._VerzusItem4 = default(EntityRef<VerzusItem>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VerzusItemType")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class VerzusItemType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemTypeId;
		
		private string _ItemTypeDesc;
		
		private EntitySet<VerzusItem> _VerzusItems;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemTypeIdChanging(int value);
    partial void OnItemTypeIdChanged();
    partial void OnItemTypeDescChanging(string value);
    partial void OnItemTypeDescChanged();
    #endregion
		
		public VerzusItemType()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ItemTypeId
		{
			get
			{
				return this._ItemTypeId;
			}
			set
			{
				if ((this._ItemTypeId != value))
				{
					this.OnItemTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ItemTypeId = value;
					this.SendPropertyChanged("ItemTypeId");
					this.OnItemTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemTypeDesc", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string ItemTypeDesc
		{
			get
			{
				return this._ItemTypeDesc;
			}
			set
			{
				if ((this._ItemTypeDesc != value))
				{
					this.OnItemTypeDescChanging(value);
					this.SendPropertyChanging();
					this._ItemTypeDesc = value;
					this.SendPropertyChanged("ItemTypeDesc");
					this.OnItemTypeDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItemType_VerzusItem", Storage="_VerzusItems", ThisKey="ItemTypeId", OtherKey="ItemType")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3, EmitDefaultValue=false)]
		public EntitySet<VerzusItem> VerzusItems
		{
			get
			{
				if ((this.serializing 
							&& (this._VerzusItems.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._VerzusItems;
			}
			set
			{
				this._VerzusItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VerzusItems(VerzusItem entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItemType = this;
		}
		
		private void detach_VerzusItems(VerzusItem entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItemType = null;
		}
		
		private void Initialize()
		{
			this._VerzusItems = new EntitySet<VerzusItem>(new Action<VerzusItem>(this.attach_VerzusItems), new Action<VerzusItem>(this.detach_VerzusItems));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VerzusItem")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class VerzusItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ItemId;
		
		private int _ItemType;
		
		private string _ItemContent;
		
		private System.DateTime _ItemDateAdded;
		
		private EntitySet<Verzus> _Verzus;
		
		private EntitySet<Verzus> _Verzus1;
		
		private EntitySet<Verzus> _Verzus2;
		
		private EntityRef<VerzusItemType> _VerzusItemType;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemIdChanging(long value);
    partial void OnItemIdChanged();
    partial void OnItemTypeChanging(int value);
    partial void OnItemTypeChanged();
    partial void OnItemContentChanging(string value);
    partial void OnItemContentChanged();
    partial void OnItemDateAddedChanging(System.DateTime value);
    partial void OnItemDateAddedChanged();
    #endregion
		
		public VerzusItem()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public long ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemType", DbType="Int NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public int ItemType
		{
			get
			{
				return this._ItemType;
			}
			set
			{
				if ((this._ItemType != value))
				{
					if (this._VerzusItemType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnItemTypeChanging(value);
					this.SendPropertyChanging();
					this._ItemType = value;
					this.SendPropertyChanged("ItemType");
					this.OnItemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemContent", DbType="NChar(300) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string ItemContent
		{
			get
			{
				return this._ItemContent;
			}
			set
			{
				if ((this._ItemContent != value))
				{
					this.OnItemContentChanging(value);
					this.SendPropertyChanging();
					this._ItemContent = value;
					this.SendPropertyChanged("ItemContent");
					this.OnItemContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDateAdded", DbType="DateTime NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.DateTime ItemDateAdded
		{
			get
			{
				return this._ItemDateAdded;
			}
			set
			{
				if ((this._ItemDateAdded != value))
				{
					this.OnItemDateAddedChanging(value);
					this.SendPropertyChanging();
					this._ItemDateAdded = value;
					this.SendPropertyChanged("ItemDateAdded");
					this.OnItemDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus", Storage="_Verzus", ThisKey="ItemId", OtherKey="VerzusItem1")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5, EmitDefaultValue=false)]
		public EntitySet<Verzus> Verzus
		{
			get
			{
				if ((this.serializing 
							&& (this._Verzus.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Verzus;
			}
			set
			{
				this._Verzus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus1", Storage="_Verzus1", ThisKey="ItemId", OtherKey="VerzusItem2")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6, EmitDefaultValue=false)]
		public EntitySet<Verzus> Verzus1
		{
			get
			{
				if ((this.serializing 
							&& (this._Verzus1.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Verzus1;
			}
			set
			{
				this._Verzus1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItem_Verzus2", Storage="_Verzus2", ThisKey="ItemId", OtherKey="VerzusItemContext")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7, EmitDefaultValue=false)]
		public EntitySet<Verzus> Verzus2
		{
			get
			{
				if ((this.serializing 
							&& (this._Verzus2.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._Verzus2;
			}
			set
			{
				this._Verzus2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VerzusItemType_VerzusItem", Storage="_VerzusItemType", ThisKey="ItemType", OtherKey="ItemTypeId", IsForeignKey=true)]
		public VerzusItemType VerzusItemType
		{
			get
			{
				return this._VerzusItemType.Entity;
			}
			set
			{
				VerzusItemType previousValue = this._VerzusItemType.Entity;
				if (((previousValue != value) 
							|| (this._VerzusItemType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VerzusItemType.Entity = null;
						previousValue.VerzusItems.Remove(this);
					}
					this._VerzusItemType.Entity = value;
					if ((value != null))
					{
						value.VerzusItems.Add(this);
						this._ItemType = value.ItemTypeId;
					}
					else
					{
						this._ItemType = default(int);
					}
					this.SendPropertyChanged("VerzusItemType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Verzus(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem = this;
		}
		
		private void detach_Verzus(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem = null;
		}
		
		private void attach_Verzus1(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem3 = this;
		}
		
		private void detach_Verzus1(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem3 = null;
		}
		
		private void attach_Verzus2(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem4 = this;
		}
		
		private void detach_Verzus2(Verzus entity)
		{
			this.SendPropertyChanging();
			entity.VerzusItem4 = null;
		}
		
		private void Initialize()
		{
			this._Verzus = new EntitySet<Verzus>(new Action<Verzus>(this.attach_Verzus), new Action<Verzus>(this.detach_Verzus));
			this._Verzus1 = new EntitySet<Verzus>(new Action<Verzus>(this.attach_Verzus1), new Action<Verzus>(this.detach_Verzus1));
			this._Verzus2 = new EntitySet<Verzus>(new Action<Verzus>(this.attach_Verzus2), new Action<Verzus>(this.detach_Verzus2));
			this._VerzusItemType = default(EntityRef<VerzusItemType>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
}
#pragma warning restore 1591
